# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

env:
  PORT: ${{ secrets.PORT }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

on:
  push:
    branches: [ alpha ]
    
jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: yarn install
    - name: 'Lint the application'
      run: yarn lint
    - name: 'Run database migration'
      run: npx prisma db push --preview-feature
      env: 
        DATABASE_URL: ${{ env.DATABASE_URL }}
        PORT: ${{ env.PORT }}
    - name: 'Create env file'
      run: |
        cat > .env <<- "EOF"
        PORT=${{ env.PORT }}
        DATABASE_URL=${{ env.DATABASE_URL }}
        EOF
    - name: 'Build the application'
      run: yarn build
    - name: 'Restart the server'
      run: pm2 restart BackendAPI
