# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

env:
  PORT: ${{ secrets.PORT }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  COOKIE: ${{ secrets.COOKIE }}
  COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
  DB_SESSIONS: ${{ secrets.DB_SESSIONS }}
  DB_URI: ${{ secrets.DB_URI }}
  DB_NAME: ${{ secrets.DB_NAME }}
  ORIGIN: ${{ secrets.ORIGIN }}

on:
  push:
    branches: [ alpha ]
    
jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: yarn install
    - name: 'Lint the application'
      run: yarn lint
    - name: 'Run database migration'
      run: npx prisma db push --preview-feature
      env: 
        DATABASE_URL: ${{ env.DATABASE_URL }}
        PORT: ${{ env.PORT }}
    - name: 'Create env file'
      run: |
        cat > .env <<- "EOF"
        DATABASE_URL=${{ env.DATABASE_URL }}
        COOKIE=${{ env.COOKIE }}
        COOKIE_NAME=${{ env.COOKIE_NAME }}
        DB_SESSIONS=${{ env.DB_SESSIONS }}
        DB_URI=${{ env.DB_URI }}
        DB_NAME=${{ env.DB_NAME }}
        ORIGIN=${{ env.ORIGIN }}
        EOF
    - name: 'Build the application'
      run: yarn build
    - name: 'Restart the server'
      run: pm2 restart BackendAPI
