# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ alpha ]
    
jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: yarn install
    - name: 'Lint the application'
      run: yarn lint
    - name: 'Run migration'
      env: 
        DATABASE_URL: ${{secrets.DATABASE_URL}}
        PORT: ${{secrets.PORT}}
      run: npx prisma migrate dev --backend init --preview-feature
    - name: 'Build the application'
      run: yarn build
    - name: 'Restart the server'
      run: pm2 restart BackendAPI
